/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LoginLayoutImport } from './routes/login/_layout'
import { Route as LoginLayoutIndexImport } from './routes/login/_layout/index'
import { Route as LayoutTransactionsIndexImport } from './routes/_layout/transactions_/index'
import { Route as LayoutSalesIndexImport } from './routes/_layout/sales_/index'
import { Route as LayoutReportsIndexImport } from './routes/_layout/reports_/index'
import { Route as LayoutPayrollsIndexImport } from './routes/_layout/payrolls_/index'
import { Route as LayoutInventoryIndexImport } from './routes/_layout/inventory_/index'
import { Route as LayoutEmployeesIndexImport } from './routes/_layout/employees_/index'
import { Route as LayoutChequesIndexImport } from './routes/_layout/cheques_/index'

// Create Virtual Routes

const LoginImport = createFileRoute('/login')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LoginRoute,
} as any)

const LoginLayoutIndexRoute = LoginLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const LayoutTransactionsIndexRoute = LayoutTransactionsIndexImport.update({
  path: '/transactions/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesIndexRoute = LayoutSalesIndexImport.update({
  path: '/sales/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsIndexRoute = LayoutReportsIndexImport.update({
  path: '/reports/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPayrollsIndexRoute = LayoutPayrollsIndexImport.update({
  path: '/payrolls/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryIndexRoute = LayoutInventoryIndexImport.update({
  path: '/inventory/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEmployeesIndexRoute = LayoutEmployeesIndexImport.update({
  path: '/employees/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChequesIndexRoute = LayoutChequesIndexImport.update({
  path: '/cheques/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout': {
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof LoginRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/cheques/': {
      preLoaderRoute: typeof LayoutChequesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/employees/': {
      preLoaderRoute: typeof LayoutEmployeesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory/': {
      preLoaderRoute: typeof LayoutInventoryIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/payrolls/': {
      preLoaderRoute: typeof LayoutPayrollsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/': {
      preLoaderRoute: typeof LayoutReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/': {
      preLoaderRoute: typeof LayoutSalesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/transactions/': {
      preLoaderRoute: typeof LayoutTransactionsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/login/_layout/': {
      preLoaderRoute: typeof LoginLayoutIndexImport
      parentRoute: typeof LoginLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutIndexRoute,
    LayoutChequesIndexRoute,
    LayoutEmployeesIndexRoute,
    LayoutInventoryIndexRoute,
    LayoutPayrollsIndexRoute,
    LayoutReportsIndexRoute,
    LayoutSalesIndexRoute,
    LayoutTransactionsIndexRoute,
  ]),
  LoginRoute.addChildren([
    LoginLayoutRoute.addChildren([LoginLayoutIndexRoute]),
  ]),
])

/* prettier-ignore-end */
